### ISSUE TITLE
Error: Cannot find module 'import-cost'

### ISSUE THREAD

**Issue by luwes** [julianburr/sublime-import-cost#3]
Thanks for a great plugin!

Trying to install I'm getting this in the Sublime console on MacOS 10.13.2, Node 8.9.1.

```
Error: Cannot find module 'import-cost'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/wes/Library/Application Support/Sublime Text 3/Packages/Import Cost/import-cost.js:1:107)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 425, in on_load
    attach_view(v)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 276, in attach_view
    check_view_event_listeners(view)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 270, in check_view_event_listeners
    listeners.append(cls(view))
  File "/Users/wes/Library/Application Support/Sublime Text 3/Packages/Import Cost/import-cost.py", line 26, in __init__
    self.update_phantoms()
  File "/Users/wes/Library/Application Support/Sublime Text 3/Packages/Import Cost/import-cost.py", line 39, in update_phantoms
    self.calc_imports(imports)
  File "/Users/wes/Library/Application Support/Sublime Text 3/Packages/Import Cost/import-cost.py", line 77, in calc_imports
    json_data = json.loads(data)
  File "./python3.3/json/__init__.py", line 316, in loads
  File "./python3.3/json/decoder.py", line 351, in decode
TypeError: expected string or buffer
```

**Comment by luwes** [comment]
`NODE_PATH` path was empty. Fixed by adding this to .bash_profile

```
export NODE_PATH="$HOME/.config/yarn/global/node_modules";
export NODE_PATH="$NODE_PATH:/usr/local/lib/node_modules";
```

**Comment by dortamiguel** [comment]
Hi,

I added to .bash_profile the NODE_PATH but it´s not working

**Comment by dortamiguel** [comment]
I went to the plugin folder and run "npm i", now it works.
